server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  thymeleaf:
    mode: HTML
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    enabled: true
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://39.106.33.181:3306/exam?characterEncoding=UTF-8&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    # 下面为连接池的补充设置，应用到上面所有数据源中
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  jpa:
    database: MySQL
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
  redis:
    timeout: 10000 #客户端超时时间单位是毫秒 默认是2000
    maxIdle: 300 #最大空闲数
    maxTotal: 1000 #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
    maxWaitMillis: 1000 #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    minEvictableIdleTimeMillis: 300000 #连接的最小空闲时间 默认1800000毫秒(30分钟)
    numTestsPerEvictionRun: 1024 #每次释放连接的最大数目,默认3
    timeBetweenEvictionRunsMillis: 30000 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    testOnBorrow: true #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testWhileIdle: true #在空闲时检查有效性, 默认false
    cluster:
      nodes: 118.190.156.52:7000,118.190.156.52:7001,118.190.156.52:7002,118.190.156.52:7003,118.190.156.52:7004,118.190.156.52:7005,118.190.156.52:7006,118.190.156.52:7007,118.190.156.52:7008
      max-redirects: 10
    password: RedisDuochuang
logging:
  level:
    com.cgb.mapper.UserMapper: debug
picPath:
  rootPath: e:/
  childPath: yilanpic
ChatServer:
  #  url: 45.76.55.67
  port: 8090
  uri: /chat